### ISSUE TITLE
Unable to start sshch, if folder ~/.config doesn't exist

### ISSUE THREAD

**Issue by ObSec** [zlaxy/sshch#10]
https://github.com/zlaxy/sshch/blob/ba9fa303ba6bcd1ba58973bd91a6bd6ba8e7ed12/sshch/sshch#L791

Start without ~/.config folder returns
Traceback (most recent call last):
  File "/usr/local/bin/sshch", line 791, in <module>
    open(conf_file, 'w')
IOError: [Errno 2] No such file or directory: '/home/user/.config/sshch.conf'

Might help:
conf_dir = os.path.expanduser("~") + '/.config'
if not os.path.exists(conf_dir):
     os.makedirs(conf_dir)

**Comment by zlaxy** [comment]
@ObSec , thanks, fixed in main repository: https://gitlab.com/zlax/sshch/commit/0fd4ff9b74527ad0c3155f521c89fc9ad87c2033#f48a8759231e000660b4ebcd489bb369bcf57d4f
Please, note: with this branch you need to update your passwords in sshch.conf (set passwords for aliases again)
`git clone https://gitlab.com/zlax/sshch`
I plan to update this Microsoft GitHub repository only with new releases. Everything new is on gitlab. Please, close this issue after testing fix.

**Comment by ObSec** [comment]
did a short test, works well. thank you
