### ISSUE TITLE
bad interpreter

### ISSUE THREAD

**Issue by Wqrld** [zlaxy/sshch#8]
`bash: /d/Program Files/newpython/Scripts/sshch: d:\program: bad interpreter: No such file or directory`
when running sshch after installing it with pip

**Comment by zlaxy** [comment]
@Wqrld Did you try to run sshch in Windows?
Sshch made for *nix systems.
If you need Windows version of sshch - i could help you to do it. But i have no installed Windows. I could consult you about sshch code, touch you to a part of platform-specific code.

**Comment by Wqrld** [comment]
Oh okay, yes I did try to use it on windows. If it is easy to do you can try making a windows version and i will test it but it would be a lot of work it's not needed.

**Comment by zlaxy** [comment]
@Wqrld I do not have any installed Windows here. 
I think for this task you can use [WSL in Windows 10](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) with installed ssh, sshpass, bazh or zsh packages. Also i recommend to run sshch from a directory with simple path without spaces in this case, because your error says that the first part of the path before space is perceived as a separate command. This is a problem in processing difference of paths with spaces under Windows and Unix.

Please close this issue if native Windows version of sshch is uncritical for you.

**Comment by Wqrld** [comment]
it's not critical. i will try to use wsl
